site:
  title: Tomee Documentation
  url: https://tomee.apache.org
  start_page: 8.0@tomee:ROOT:docs.adoc
content:
  sources:
# I have been working against a branch off of master branch. Would branching off develop be more appropriate?
  - url: ./../
    start_path: docs/tomee
    branches: HEAD

    # This uses the local copy. I think you need to explicitly set up local branches for these, tracking the remotes.
    # Even using git worktree, the path must be to the main git checkout.
  - url: ./../
    # This uses the remote git.
  #- url:  https://github.com/djencks/tomee.git
    start_path: docs/tomee
    branches: [antora-tomee-7.1.x, antora-tomee-7.0.x]

  # currently producing version master
  - url: ./../../tomee-site-generator
#  - url: https://github.com/djencks/tomee-site-generator.git
    start_path: tomee
    branches: antora

  - url: ./../../tomee-site
#  - url: https://github.com/djencks/tomee-site.git
    start_path: tomee
    branches: antora

# The .adoc files for the examples are not checked in; they are copied and renamed from ../examples.
# You need to run update-examples.sh to generate the copy scripts and nav files and show you if there are new or removed pages.
  - url: ./../
    start_path: docs/examples-en
    branches: HEAD

  - url: ./../
    start_path: docs/examples-es
    branches: HEAD

  - url: ./../
    start_path: docs/examples-pt
    branches: HEAD

asciidoc:
  attributes:
    common-vc: master@common
    examples-vc: 8.0@examples
    tomee-latest-vc: 8.0@tomee
    supported-properties-table-layout: cols="2,1,3,5a",options="header"
    properties-table-layout: cols="3a,2a,5a",options="header"
    name-description-table-layout: cols="2,7a",options="header"


# This is the Antora default UI.
# We need to modify it with supplemental files or replace it.
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true

#log:
#  console:
#    level: info
#  formatString: 'version: ${version} component: ${component} file: ${file} path ${path} lineno: ${lineno} message: ${message}'
