#!/bin/bash

mkdir -p examples-pt/modules/ROOT/pages

cp ../examples/README.adoc examples-pt/modules/ROOT/pages/index.adoc


cp ../examples/access-timeout-meta/README_pt.adoc examples-pt/modules/ROOT/pages/access-timeout-meta.adoc
cp ../examples/access-timeout/README_pt.adoc examples-pt/modules/ROOT/pages/access-timeout.adoc
cp ../examples/alternate-descriptors/README_pt.adoc examples-pt/modules/ROOT/pages/alternate-descriptors.adoc
cp ../examples/application-composer/README_pt.adoc examples-pt/modules/ROOT/pages/application-composer.adoc
cp ../examples/applicationcomposer-jaxws-cdi/README_pt.adoc examples-pt/modules/ROOT/pages/applicationcomposer-jaxws-cdi.adoc
cp ../examples/applicationexception/README_pt.adoc examples-pt/modules/ROOT/pages/applicationexception.adoc
cp ../examples/arquillian-jpa/README_pt.adoc examples-pt/modules/ROOT/pages/arquillian-jpa.adoc
cp ../examples/async-methods/README_pt.adoc examples-pt/modules/ROOT/pages/async-methods.adoc
cp ../examples/async-postconstruct/README_pt.adoc examples-pt/modules/ROOT/pages/async-postconstruct.adoc
cp ../examples/async-servlet/README_pt.adoc examples-pt/modules/ROOT/pages/async-servlet.adoc
cp ../examples/bean-validation-design-by-contract/README_pt.adoc examples-pt/modules/ROOT/pages/bean-validation-design-by-contract.adoc
cp ../examples/cdi-alternative-and-stereotypes/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-alternative-and-stereotypes.adoc
cp ../examples/cdi-application-scope/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-application-scope.adoc
cp ../examples/cdi-basic/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-basic.adoc
cp ../examples/cdi-dynamic-inject/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-dynamic-inject.adoc
cp ../examples/cdi-events/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-events.adoc
cp ../examples/cdi-interceptors/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-interceptors.adoc
cp ../examples/cdi-produces-disposes/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-produces-disposes.adoc
cp ../examples/cdi-produces-field/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-produces-field.adoc
cp ../examples/cdi-qualifier/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-qualifier.adoc
cp ../examples/cdi-realm/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-realm.adoc
cp ../examples/cdi-request-scope/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-request-scope.adoc
cp ../examples/cdi-session-scope/README_pt.adoc examples-pt/modules/ROOT/pages/cdi-session-scope.adoc
cp ../examples/change-jaxws-url/README_pt.adoc examples-pt/modules/ROOT/pages/change-jaxws-url.adoc
cp ../examples/cloud-tomee-azure/README_pt.adoc examples-pt/modules/ROOT/pages/cloud-tomee-azure.adoc
cp ../examples/concurrency-utils/README_pt.adoc examples-pt/modules/ROOT/pages/concurrency-utils.adoc
cp ../examples/cucumber-jvm/README_pt.adoc examples-pt/modules/ROOT/pages/cucumber-jvm.adoc
cp ../examples/datasource-ciphered-password/README_pt.adoc examples-pt/modules/ROOT/pages/datasource-ciphered-password.adoc
cp ../examples/datasource-versioning/README_pt.adoc examples-pt/modules/ROOT/pages/datasource-versioning.adoc
cp ../examples/deltaspike-fullstack/README_pt.adoc examples-pt/modules/ROOT/pages/deltaspike-fullstack.adoc
cp ../examples/deltaspike-i18n/README_pt.adoc examples-pt/modules/ROOT/pages/deltaspike-i18n.adoc
cp ../examples/dynamic-dao-implementation/README_pt.adoc examples-pt/modules/ROOT/pages/dynamic-dao-implementation.adoc
cp ../examples/dynamic-datasource-routing/README_pt.adoc examples-pt/modules/ROOT/pages/dynamic-datasource-routing.adoc
cp ../examples/javamail/README_pt.adoc examples-pt/modules/ROOT/pages/javamail.adoc
cp ../examples/jpa-eclipselink/README_pt.adoc examples-pt/modules/ROOT/pages/jpa-eclipselink.adoc
cp ../examples/jpa-enumerated/README_pt.adoc examples-pt/modules/ROOT/pages/jpa-enumerated.adoc
cp ../examples/jpa-hibernate/README_pt.adoc examples-pt/modules/ROOT/pages/jpa-hibernate.adoc
cp ../examples/jsf-cdi-and-ejb/README_pt.adoc examples-pt/modules/ROOT/pages/jsf-cdi-and-ejb.adoc
cp ../examples/mp-config-example/README_pt.adoc examples-pt/modules/ROOT/pages/mp-config-example.adoc
cp ../examples/mp-custom-healthcheck/README_pt.adoc examples-pt/modules/ROOT/pages/mp-custom-healthcheck.adoc
cp ../examples/mp-faulttolerance-fallback/README_pt.adoc examples-pt/modules/ROOT/pages/mp-faulttolerance-fallback.adoc
cp ../examples/mp-faulttolerance-retry/README_pt.adoc examples-pt/modules/ROOT/pages/mp-faulttolerance-retry.adoc
cp ../examples/mp-faulttolerance-timeout/README_pt.adoc examples-pt/modules/ROOT/pages/mp-faulttolerance-timeout.adoc
cp ../examples/mvc-cxf-hibernate/README_pt.adoc examples-pt/modules/ROOT/pages/mvc-cxf-hibernate.adoc
cp ../examples/simple-cdi-interceptor/README_pt.adoc examples-pt/modules/ROOT/pages/simple-cdi-interceptor.adoc
cp ../examples/simple-remote-tomcatusers/README_pt.adoc examples-pt/modules/ROOT/pages/simple-remote-tomcatusers.adoc
cp ../examples/simple-rest/README_pt.adoc examples-pt/modules/ROOT/pages/simple-rest.adoc
cp ../examples/spring-data-proxy-meta/README_pt.adoc examples-pt/modules/ROOT/pages/spring-data-proxy-meta.adoc
cp ../examples/spring-data-proxy/README_pt.adoc examples-pt/modules/ROOT/pages/spring-data-proxy.adoc
cp ../examples/testing-security/README_pt.adoc examples-pt/modules/ROOT/pages/testing-security.adoc
cp ../examples/tomee-jms-portability/README_pt.adoc examples-pt/modules/ROOT/pages/tomee-jms-portability.adoc
cp ../examples/vaadin-lts-v08-simple/README_pt.adoc examples-pt/modules/ROOT/pages/vaadin-lts-v08-simple.adoc
cp ../examples/vaadin-lts-v10-simple/README_pt.adoc examples-pt/modules/ROOT/pages/vaadin-lts-v10-simple.adoc
cp ../examples/webservice-ssl-client-cert/README_pt.adoc examples-pt/modules/ROOT/pages/webservice-ssl-client-cert.adoc
cp ../examples/websocket-tls-basic-auth/README_pt.adoc examples-pt/modules/ROOT/pages/websocket-tls-basic-auth.adoc
