#!/bin/bash

mkdir -p examples-en/modules/ROOT/pages


cp ../examples/README.adoc examples-en/modules/ROOT/../examples/README.adoc.adoc
cp ../examples/access-timeout-meta/README.adoc examples-en/modules/ROOT/access-timeout-meta.adoc
cp ../examples/access-timeout/README.adoc examples-en/modules/ROOT/access-timeout.adoc
cp ../examples/alternate-descriptors/README.adoc examples-en/modules/ROOT/alternate-descriptors.adoc
cp ../examples/applet/README.adoc examples-en/modules/ROOT/applet.adoc
cp ../examples/application-composer/README.adoc examples-en/modules/ROOT/application-composer.adoc
cp ../examples/applicationcomposer-jaxws-cdi/README.adoc examples-en/modules/ROOT/applicationcomposer-jaxws-cdi.adoc
cp ../examples/applicationexception/README.adoc examples-en/modules/ROOT/applicationexception.adoc
cp ../examples/arquillian-jpa/README.adoc examples-en/modules/ROOT/arquillian-jpa.adoc
cp ../examples/async-methods/README.adoc examples-en/modules/ROOT/async-methods.adoc
cp ../examples/async-postconstruct/README.adoc examples-en/modules/ROOT/async-postconstruct.adoc
cp ../examples/async-servlet/README.adoc examples-en/modules/ROOT/async-servlet.adoc
cp ../examples/bean-validation-design-by-contract/README.adoc examples-en/modules/ROOT/bean-validation-design-by-contract.adoc
cp ../examples/bval-evaluation-redeployment/README.adoc examples-en/modules/ROOT/bval-evaluation-redeployment.adoc
cp ../examples/cdi-alternative-and-stereotypes/README.adoc examples-en/modules/ROOT/cdi-alternative-and-stereotypes.adoc
cp ../examples/cdi-application-scope/README.adoc examples-en/modules/ROOT/cdi-application-scope.adoc
cp ../examples/cdi-basic/README.adoc examples-en/modules/ROOT/cdi-basic.adoc
cp ../examples/cdi-dynamic-inject/README.adoc examples-en/modules/ROOT/cdi-dynamic-inject.adoc
cp ../examples/cdi-events/README.adoc examples-en/modules/ROOT/cdi-events.adoc
cp ../examples/cdi-interceptors/README.adoc examples-en/modules/ROOT/cdi-interceptors.adoc
cp ../examples/cdi-produces-disposes/README.adoc examples-en/modules/ROOT/cdi-produces-disposes.adoc
cp ../examples/cdi-produces-field/README.adoc examples-en/modules/ROOT/cdi-produces-field.adoc
cp ../examples/cdi-qualifier/README.adoc examples-en/modules/ROOT/cdi-qualifier.adoc
cp ../examples/cdi-realm/README.adoc examples-en/modules/ROOT/cdi-realm.adoc
cp ../examples/cdi-request-scope/README.adoc examples-en/modules/ROOT/cdi-request-scope.adoc
cp ../examples/cdi-session-scope/README.adoc examples-en/modules/ROOT/cdi-session-scope.adoc
cp ../examples/change-jaxws-url/README.adoc examples-en/modules/ROOT/change-jaxws-url.adoc
cp ../examples/cloud-tomee-azure/README.adoc examples-en/modules/ROOT/cloud-tomee-azure.adoc
cp ../examples/component-interfaces/README.adoc examples-en/modules/ROOT/component-interfaces.adoc
cp ../examples/concurrency-utils/README.adoc examples-en/modules/ROOT/concurrency-utils.adoc
cp ../examples/connector-war/README.adoc examples-en/modules/ROOT/connector-war.adoc
cp ../examples/cucumber-jvm/README.adoc examples-en/modules/ROOT/cucumber-jvm.adoc
cp ../examples/custom-injection/README.adoc examples-en/modules/ROOT/custom-injection.adoc
cp ../examples/datasource-ciphered-password/README.adoc examples-en/modules/ROOT/datasource-ciphered-password.adoc
cp ../examples/datasource-versioning/README.adoc examples-en/modules/ROOT/datasource-versioning.adoc
cp ../examples/decorators/README.adoc examples-en/modules/ROOT/decorators.adoc
cp ../examples/deltaspike-fullstack/README.adoc examples-en/modules/ROOT/deltaspike-fullstack.adoc
cp ../examples/deltaspike-i18n/README.adoc examples-en/modules/ROOT/deltaspike-i18n.adoc
cp ../examples/dynamic-dao-implementation/README.adoc examples-en/modules/ROOT/dynamic-dao-implementation.adoc
cp ../examples/dynamic-datasource-routing/README.adoc examples-en/modules/ROOT/dynamic-datasource-routing.adoc
cp ../examples/dynamic-implementation/README.adoc examples-en/modules/ROOT/dynamic-implementation.adoc
cp ../examples/dynamic-proxy-to-access-mbean/README.adoc examples-en/modules/ROOT/dynamic-proxy-to-access-mbean.adoc
cp ../examples/ear-testing/README.adoc examples-en/modules/ROOT/ear-testing.adoc
cp ../examples/ejb-examples/README.adoc examples-en/modules/ROOT/ejb-examples.adoc
cp ../examples/ejb-remote-call-2/README.adoc examples-en/modules/ROOT/ejb-remote-call-2.adoc
cp ../examples/ejb-remote-call/README.adoc examples-en/modules/ROOT/ejb-remote-call.adoc
cp ../examples/ejb-webservice/README.adoc examples-en/modules/ROOT/ejb-webservice.adoc
cp ../examples/groovy-jpa/README.adoc examples-en/modules/ROOT/groovy-jpa.adoc
cp ../examples/groovy-spock/README.adoc examples-en/modules/ROOT/groovy-spock.adoc
cp ../examples/helloworld-weblogic/README.adoc examples-en/modules/ROOT/helloworld-weblogic.adoc
cp ../examples/injection-of-connectionfactory/README.adoc examples-en/modules/ROOT/injection-of-connectionfactory.adoc
cp ../examples/injection-of-datasource/README.adoc examples-en/modules/ROOT/injection-of-datasource.adoc
cp ../examples/injection-of-ejbs/README.adoc examples-en/modules/ROOT/injection-of-ejbs.adoc
cp ../examples/injection-of-entitymanager/README.adoc examples-en/modules/ROOT/injection-of-entitymanager.adoc
cp ../examples/injection-of-env-entry/README.adoc examples-en/modules/ROOT/injection-of-env-entry.adoc
cp ../examples/interceptors/README.adoc examples-en/modules/ROOT/interceptors.adoc
cp ../examples/java-modules/README.adoc examples-en/modules/ROOT/java-modules.adoc
cp ../examples/javamail/README.adoc examples-en/modules/ROOT/javamail.adoc
cp ../examples/jaxrs-filter/README.adoc examples-en/modules/ROOT/jaxrs-filter.adoc
cp ../examples/jaxrs-json-provider-jettison/README.adoc examples-en/modules/ROOT/jaxrs-json-provider-jettison.adoc
cp ../examples/jpa-eclipselink/README.adoc examples-en/modules/ROOT/jpa-eclipselink.adoc
cp ../examples/jpa-enumerated/README.adoc examples-en/modules/ROOT/jpa-enumerated.adoc
cp ../examples/jpa-hibernate/README.adoc examples-en/modules/ROOT/jpa-hibernate.adoc
cp ../examples/jsf-cdi-and-ejb/README.adoc examples-en/modules/ROOT/jsf-cdi-and-ejb.adoc
cp ../examples/jsf-managedBean-and-ejb/README.adoc examples-en/modules/ROOT/jsf-managedBean-and-ejb.adoc
cp ../examples/jsonb-configuration/README.adoc examples-en/modules/ROOT/jsonb-configuration.adoc
cp ../examples/jsonb-custom-serializer/README.adoc examples-en/modules/ROOT/jsonb-custom-serializer.adoc
cp ../examples/lookup-of-ejbs-with-descriptor/README.adoc examples-en/modules/ROOT/lookup-of-ejbs-with-descriptor.adoc
cp ../examples/lookup-of-ejbs/README.adoc examples-en/modules/ROOT/lookup-of-ejbs.adoc
cp ../examples/mbean-auto-registration/README.adoc examples-en/modules/ROOT/mbean-auto-registration.adoc
cp ../examples/moviefun-rest/README.adoc examples-en/modules/ROOT/moviefun-rest.adoc
cp ../examples/moviefun/README.adoc examples-en/modules/ROOT/moviefun.adoc
cp ../examples/movies-complete-meta/README.adoc examples-en/modules/ROOT/movies-complete-meta.adoc
cp ../examples/movies-complete/README.adoc examples-en/modules/ROOT/movies-complete.adoc
cp ../examples/mp-config-example/README.adoc examples-en/modules/ROOT/mp-config-example.adoc
cp ../examples/mp-config-source-database/README.adoc examples-en/modules/ROOT/mp-config-source-database.adoc
cp ../examples/mp-custom-healthcheck/README.adoc examples-en/modules/ROOT/mp-custom-healthcheck.adoc
cp ../examples/mp-faulttolerance-fallback/README.adoc examples-en/modules/ROOT/mp-faulttolerance-fallback.adoc
cp ../examples/mp-faulttolerance-retry/README.adoc examples-en/modules/ROOT/mp-faulttolerance-retry.adoc
cp ../examples/mp-faulttolerance-timeout/README.adoc examples-en/modules/ROOT/mp-faulttolerance-timeout.adoc
cp ../examples/mp-jsonb-configuration/README.adoc examples-en/modules/ROOT/mp-jsonb-configuration.adoc
cp ../examples/mp-jwt-bean-validation-strongly-typed/README.adoc examples-en/modules/ROOT/mp-jwt-bean-validation-strongly-typed.adoc
cp ../examples/mp-jwt-bean-validation/README.adoc examples-en/modules/ROOT/mp-jwt-bean-validation.adoc
cp ../examples/mp-metrics-counted/README.adoc examples-en/modules/ROOT/mp-metrics-counted.adoc
cp ../examples/mp-metrics-gauge/README.adoc examples-en/modules/ROOT/mp-metrics-gauge.adoc
cp ../examples/mp-metrics-histogram/README.adoc examples-en/modules/ROOT/mp-metrics-histogram.adoc
cp ../examples/mp-metrics-metered/README.adoc examples-en/modules/ROOT/mp-metrics-metered.adoc
cp ../examples/mp-metrics-timed/README.adoc examples-en/modules/ROOT/mp-metrics-timed.adoc
cp ../examples/mp-opentracing-traced/README.adoc examples-en/modules/ROOT/mp-opentracing-traced.adoc
cp ../examples/mp-rest-client/README.adoc examples-en/modules/ROOT/mp-rest-client.adoc
cp ../examples/mp-rest-jwt-jwk/README.adoc examples-en/modules/ROOT/mp-rest-jwt-jwk.adoc
cp ../examples/mp-rest-jwt-principal/README.adoc examples-en/modules/ROOT/mp-rest-jwt-principal.adoc
cp ../examples/mp-rest-jwt-public-key/README.adoc examples-en/modules/ROOT/mp-rest-jwt-public-key.adoc
cp ../examples/mp-rest-jwt/README.adoc examples-en/modules/ROOT/mp-rest-jwt.adoc
cp ../examples/mtom/README.adoc examples-en/modules/ROOT/mtom.adoc
cp ../examples/multi-jpa-provider-testing/README.adoc examples-en/modules/ROOT/multi-jpa-provider-testing.adoc
cp ../examples/multiple-tomee-arquillian/README.adoc examples-en/modules/ROOT/multiple-tomee-arquillian.adoc
cp ../examples/mvc-cxf-hibernate/README.adoc examples-en/modules/ROOT/mvc-cxf-hibernate.adoc
cp ../examples/mvc-cxf/README.adoc examples-en/modules/ROOT/mvc-cxf.adoc
cp ../examples/mvc-resteasy/README.adoc examples-en/modules/ROOT/mvc-resteasy.adoc
cp ../examples/myfaces-codi-demo/README.adoc examples-en/modules/ROOT/myfaces-codi-demo.adoc
cp ../examples/persistence-fragment/README.adoc examples-en/modules/ROOT/persistence-fragment.adoc
cp ../examples/pojo-webservice/README.adoc examples-en/modules/ROOT/pojo-webservice.adoc
cp ../examples/polling-parent/README.adoc examples-en/modules/ROOT/polling-parent.adoc
cp ../examples/projectstage-demo/README.adoc examples-en/modules/ROOT/projectstage-demo.adoc
cp ../examples/quartz-app/README.adoc examples-en/modules/ROOT/quartz-app.adoc
cp ../examples/realm-in-tomee/README.adoc examples-en/modules/ROOT/realm-in-tomee.adoc
cp ../examples/reload-persistence-unit-properties/README.adoc examples-en/modules/ROOT/reload-persistence-unit-properties.adoc
cp ../examples/resources-declared-in-webapp/README.adoc examples-en/modules/ROOT/resources-declared-in-webapp.adoc
cp ../examples/resources-jmx-example/README.adoc examples-en/modules/ROOT/resources-jmx-example.adoc
cp ../examples/rest-applicationcomposer-mockito/README.adoc examples-en/modules/ROOT/rest-applicationcomposer-mockito.adoc
cp ../examples/rest-cdi/README.adoc examples-en/modules/ROOT/rest-cdi.adoc
cp ../examples/rest-example-with-application/README.adoc examples-en/modules/ROOT/rest-example-with-application.adoc
cp ../examples/rest-example/README.adoc examples-en/modules/ROOT/rest-example.adoc
cp ../examples/rest-on-ejb/README.adoc examples-en/modules/ROOT/rest-on-ejb.adoc
cp ../examples/rest-xml-json/README.adoc examples-en/modules/ROOT/rest-xml-json.adoc
cp ../examples/schedule-events/README.adoc examples-en/modules/ROOT/schedule-events.adoc
cp ../examples/schedule-expression/README.adoc examples-en/modules/ROOT/schedule-expression.adoc
cp ../examples/schedule-methods-meta/README.adoc examples-en/modules/ROOT/schedule-methods-meta.adoc
cp ../examples/schedule-methods/README.adoc examples-en/modules/ROOT/schedule-methods.adoc
cp ../examples/simple-cdi-interceptor/README.adoc examples-en/modules/ROOT/simple-cdi-interceptor.adoc
cp ../examples/simple-cmp2/README.adoc examples-en/modules/ROOT/simple-cmp2.adoc
cp ../examples/simple-jms/README.adoc examples-en/modules/ROOT/simple-jms.adoc
cp ../examples/simple-mdb-and-cdi/README.adoc examples-en/modules/ROOT/simple-mdb-and-cdi.adoc
cp ../examples/simple-mdb-with-descriptor/README.adoc examples-en/modules/ROOT/simple-mdb-with-descriptor.adoc
cp ../examples/simple-mdb/README.adoc examples-en/modules/ROOT/simple-mdb.adoc
cp ../examples/simple-remote-tomcatusers/README.adoc examples-en/modules/ROOT/simple-remote-tomcatusers.adoc
cp ../examples/simple-rest/README.adoc examples-en/modules/ROOT/simple-rest.adoc
cp ../examples/simple-singleton/README.adoc examples-en/modules/ROOT/simple-singleton.adoc
cp ../examples/simple-stateful-callbacks/README.adoc examples-en/modules/ROOT/simple-stateful-callbacks.adoc
cp ../examples/simple-stateful/README.adoc examples-en/modules/ROOT/simple-stateful.adoc
cp ../examples/simple-stateless-callbacks/README.adoc examples-en/modules/ROOT/simple-stateless-callbacks.adoc
cp ../examples/simple-stateless-with-descriptor/README.adoc examples-en/modules/ROOT/simple-stateless-with-descriptor.adoc
cp ../examples/simple-stateless/README.adoc examples-en/modules/ROOT/simple-stateless.adoc
cp ../examples/simple-webservice-without-interface/README.adoc examples-en/modules/ROOT/simple-webservice-without-interface.adoc
cp ../examples/simple-webservice/README.adoc examples-en/modules/ROOT/simple-webservice.adoc
cp ../examples/singleton-startup-ordering/README.adoc examples-en/modules/ROOT/singleton-startup-ordering.adoc
cp ../examples/spring-data-proxy-meta/README.adoc examples-en/modules/ROOT/spring-data-proxy-meta.adoc
cp ../examples/spring-data-proxy/README.adoc examples-en/modules/ROOT/spring-data-proxy.adoc
cp ../examples/struts/README.adoc examples-en/modules/ROOT/struts.adoc
cp ../examples/telephone-stateful/README.adoc examples-en/modules/ROOT/telephone-stateful.adoc
cp ../examples/testcase-injection/README.adoc examples-en/modules/ROOT/testcase-injection.adoc
cp ../examples/testing-security-2/README.adoc examples-en/modules/ROOT/testing-security-2.adoc
cp ../examples/testing-security-3/README.adoc examples-en/modules/ROOT/testing-security-3.adoc
cp ../examples/testing-security-4/README.adoc examples-en/modules/ROOT/testing-security-4.adoc
cp ../examples/testing-security-meta/README.adoc examples-en/modules/ROOT/testing-security-meta.adoc
cp ../examples/testing-security/README.adoc examples-en/modules/ROOT/testing-security.adoc
cp ../examples/testing-transactions-bmt/README.adoc examples-en/modules/ROOT/testing-transactions-bmt.adoc
cp ../examples/testing-transactions/README.adoc examples-en/modules/ROOT/testing-transactions.adoc
cp ../examples/tomee-jersey-eclipselink/README.adoc examples-en/modules/ROOT/tomee-jersey-eclipselink.adoc
cp ../examples/tomee-jms-portability/README.adoc examples-en/modules/ROOT/tomee-jms-portability.adoc
cp ../examples/transaction-rollback/README.adoc examples-en/modules/ROOT/transaction-rollback.adoc
cp ../examples/troubleshooting/README.adoc examples-en/modules/ROOT/troubleshooting.adoc
cp ../examples/vaadin-lts-v08-simple/README.adoc examples-en/modules/ROOT/vaadin-lts-v08-simple.adoc
cp ../examples/vaadin-lts-v10-simple/README.adoc examples-en/modules/ROOT/vaadin-lts-v10-simple.adoc
cp ../examples/vaadin-vxx-simple/README.adoc examples-en/modules/ROOT/vaadin-vxx-simple.adoc
cp ../examples/webservice-attachments/README.adoc examples-en/modules/ROOT/webservice-attachments.adoc
cp ../examples/webservice-handlerchain/README.adoc examples-en/modules/ROOT/webservice-handlerchain.adoc
cp ../examples/webservice-holder/README.adoc examples-en/modules/ROOT/webservice-holder.adoc
cp ../examples/webservice-inheritance/README.adoc examples-en/modules/ROOT/webservice-inheritance.adoc
cp ../examples/webservice-security/README.adoc examples-en/modules/ROOT/webservice-security.adoc
cp ../examples/webservice-ssl-client-cert/README.adoc examples-en/modules/ROOT/webservice-ssl-client-cert.adoc
cp ../examples/webservice-ws-security/README.adoc examples-en/modules/ROOT/webservice-ws-security.adoc
cp ../examples/webservice-ws-with-resources-config/README.adoc examples-en/modules/ROOT/webservice-ws-with-resources-config.adoc
cp ../examples/websocket-tls-basic-auth/README.adoc examples-en/modules/ROOT/websocket-tls-basic-auth.adoc
